### ISSUE TITLE
support for cassandra-driver-core 2.0.0

### ISSUE THREAD

**Issue by knight1128** [otaviojava/Easy-Cassandra#10]
Hi

Could you support cassandra-diver-core 2.0.0?
If I use the version of cassandra driver core, "Caused by: java.lang.ClassNotFoundException: com.datastax.driver.core.Query" exception is occured. 

I hope to support this~

**Comment by otaviojava** [comment]
the new version has some incompatible, but We are working it.

**Comment by otaviojava** [comment]
Done, please use the new 2.0.0-RC6 version
