### ISSUE TITLE
ColumnUtil.getFieldByColumnName cannot find index by name

### ISSUE THREAD

**Issue by letiemble** [otaviojava/Easy-Cassandra#12]
The method `ColumnUtil.getFieldByColumnName` cannot find a declared index if the field and the column have different names.

For example, if a field is declared this way:

```
@Index
@Column(name = "value")
private String fValue;
```

then the column and the index are created with name `value`.

But calling `ColumnUtil.getFieldByColumnName` with `value` throws an exception.

The line `ColumnUtil:388` has to be changed from:

```
if(index.getName().equals(columnName)){
```

to:

```
if(getColumnName(index).equals(columnName)){
```

so the behavior is correct.

**Comment by otaviojava** [comment]
Thank for the problems solved.
It was launched on RC7.
