### ISSUE TITLE
Upgrade to org.ow2.spec.ee.ow2-jpa-2.0-spec to 1.0.13

### ISSUE THREAD

**Issue by letiemble** [otaviojava/Easy-Cassandra#13]
When using hibernate-validator, an exception is thrown at initialization. The cause is missing null check located at javax.persistence.Persistence$PersistenceUtilImpl.isLoaded(Persistence.java:190).
The bug has been fixed in 1.0.13.

**Comment by otaviojava** [comment]
Did you try the newest version? the 2.0.0.
I am testing this version, if everything is ok I will update.

<dependency>
    <groupId>org.ow2.spec.ee</groupId>
    <artifactId>ow2-jpa-2.0-spec</artifactId>
    <version>2.0.0</version>
</dependency>

**Comment by otaviojava** [comment]
Done, please try on 2.0.0-RC8

**Comment by letiemble** [comment]
That works for me. Thanks.
