### ISSUE TITLE
Connecting to Cassandra with username+password

### ISSUE THREAD

**Issue by ghost** [otaviojava/Easy-Cassandra#15]
Hi there,

I don't see any way right now to pass the username/password credentials when connecting to the keyspace. Is this intentional? To support this, it seems like we would have to add a method that does something like this:

Cluster.Builder clusterBuilder = Cluster.builder()
                .addContactPoints(hostnames).withPort(port)
                .withCredentials(username, password);

**Comment by otaviojava** [comment]
not yet.

**Comment by ghost** [comment]
Ok. Do you mind if I add that feature since my project need it? It will be tricky to add unit test for it using local Cassandra but I can definitely do manual tests using our remote Cassandra setup. Will you be comfortable if there is no unit test for it since it will just be using Datastax feature anyway?

**Comment by otaviojava** [comment]
I had created two methods on CassandraFactory that connects with credentials.
What do you think?

**Comment by ghost** [comment]
Hi there,

Are the new methods in master branch? I can't seem to find them inside CassandraFactory inside master. Thank you!

**Comment by otaviojava** [comment]
Please, verify again.

**Comment by ghost** [comment]
I see it now. Is it possible to expose the username and password as constructor arguments to CassandraFactoryAnnotation so that it can be injected in Spring such that I can do

```
    <bean id="cassandraFactory" class="org.easycassandra.persistence.cassandra.spring.CassandraFactoryAnnotation">
        <constructor-arg name="host" value="localhost" />
        <constructor-arg name="keySpace" value="galaxy" />
        <constructor-arg name="username" value="abc" />
        <constructor-arg name="password" value="abc" />
        <property name="annotatedClasses">
            <list>
                  <value>com.temp.LifestyleHistory</value>
            </list>
        </property>
    </bean>
```

**Comment by otaviojava** [comment]
Done.
So what do you think now?

**Comment by ghost** [comment]
Hi,
Have the changes been checked in? I don't seem to see them

**Comment by otaviojava** [comment]
See: http://goo.gl/lX9BAJ
I will generate new version comming soon.

**Comment by ghost** [comment]
This is perfect. Thank you!

**Comment by otaviojava** [comment]
this improvement had done on version 2.0.0-RC9.
