### ISSUE TITLE
double tables in different keyspaces

### ISSUE THREAD

**Issue by sashraghi** [otaviojava/Easy-Cassandra#2]
Hi there,

first thank you for the API. My issue is that I created two different keyspaces let say
KeySpace A and KeySpace B 
and I defined TableA in KeySpaceA and TableB in KeySpaceB. and in DAO classes 
I have an instance of org.easycassandra.persistence.Persistence
with 
EasyCassandraManager.getPersistence(keySpace, IP, port);

But during testing I recognized that somehow TableB has been created in KeySpaceA and and vice versa.

My question is why Easy Cassandra created a new table in another keyspace and how can I force my entity to be  persisted in a specific keyspace and not in anther. 

I tried with

@Table(name="countrytable", schema="countryspace") but it does not work.

thank you for your time and hesitation
Saeed

**Comment by otaviojava** [comment]
thanks for your feedback.
I am working in this improvement.
I believe the best way is, how you say:
@Table(name="person",schema="schematA")

I agree with you.

**Comment by sashraghi** [comment]
Thank you Otavio for your email. It would be great if you could fix this issue, because we use your API in our project. I 'll try with the table annotation and write a comment about the result back to you.  
Cheers Saeed

**Comment by otaviojava** [comment]
I did some modifications to do that.
Please try to use, but remember that is only the beta version, thereby
we will test more and get more improvement about  that.
