### ISSUE TITLE
Index is not created using annotation @Index

### ISSUE THREAD

**Issue by ghost** [otaviojava/Easy-Cassandra#3]
Here is the Dao and the result:

@Entity
public class Log implements Serializable {
private static final long serialVersionUID = 3L;
@Id
private String uuid;
...
@Index
@Column(name = "user_uuid")
private String user_uuid;
...
// get / set
...
}

Result
cqlsh:test_lp> DESCRIBE TABLE test_cassandra.Log;

CREATE TABLE Log (
  KEY text PRIMARY KEY
) WITH
  comment='' AND
  comparator=text AND
  read_repair_chance=0.100000 AND
  gc_grace_seconds=864000 AND
  default_validation=text AND
  min_compaction_threshold=4 AND
  max_compaction_threshold=32 AND
  replicate_on_write='true' AND
  compaction_strategy_class='SizeTieredCompactionStrategy' AND
  compression_parameters:sstable_compression='SnappyCompressor';

**Comment by otaviojava** [comment]
which Easy-Cassanra's version ? and which Cassandra's version ?

**Comment by ghost** [comment]
OS: Ubuntu
Java: 1.6
Cassandra: 1.2.5 (Apache deb repo)
EasyCassandra (maven):
< dependency >
    < groupId >org.easycassandra</ groupId >
    < artifactId >EasyCassandra</ artifactId >
    < version >1.1.0-RC2</version>
</ dependency >

**Comment by otaviojava** [comment]
Thank you, for your suggestion.
I tried to simulate running this test:
https://github.com/otaviojava/Easy-Cassandra/blob/master/src/test/java/org/easycassandra/bean/LogDAOTest.java
Using this model https://github.com/otaviojava/Easy-Cassandra/blob/master/src/test/java/org/easycassandra/bean/model/Log.java

And the test passed!!!

I try using cassandra 1.2.5, ubuntu 13.04 and Openjdk 1.7.0

**Comment by ghost** [comment]
Wow, thank you for the fast response.

Although even if the creation + first object insertion is sucessfull the
Index has'nt being created.

Could you send me the result of the CQL command please:

USE <myKeyspace>;
DESCRIBE TABLE Log;

/LP

FYI
(Hello from Canada/Québec)

## 

Louis-Philippe Lebouthillier
E-mail: pokstar@gmail.com

**Comment by otaviojava** [comment]
here:

WARNING: CQL3 tables are intentionally omitted from 'describe' output.
See https://issues.apache.org/jira/browse/CASSANDRA-4377 for details.

```
ColumnFamily: Log
  Key Validation Class: org.apache.cassandra.db.marshal.UTF8Type
  Default column value validator: org.apache.cassandra.db.marshal.UTF8Type
  Columns sorted by: org.apache.cassandra.db.marshal.UTF8Type
  GC grace seconds: 864000
  Compaction min/max thresholds: 4/32
  Read repair chance: 0.1
  DC Local Read repair chance: 0.0
  Populate IO Cache on flush: false
  Replicate on write: true
  Caching: KEYS_ONLY
  Bloom Filter FP chance: default
  Built indexes: [Log.user_uuid_key]
  Column Metadata:
    Column Name: user_uuid
      Validation Class: org.apache.cassandra.db.marshal.UTF8Type
      Index Name: user_uuid_key
      Index Type: KEYS
      Index Options: {}
  Compaction Strategy: org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy
  Compression Options:
    sstable_compression: org.apache.cassandra.io.compress.SnappyCompressor
```
