### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by siwatson** [otaviojava/Easy-Cassandra#38]
Are there plans to upload the EC JARs to maven central? 

I'm working on an OSGi project which uses gradle to build bundles, requiring me to add the custom EC maven repo into each script. For now, I put the JAR in our own internal maven repo but it would be neater if they were in maven central IMHO.

**Comment by otaviojava** [comment]
I would love, but I didn't study to do that.
Can you help?

**Comment by siwatson** [comment]
It should be pretty straightforward: https://maven.apache.org/guides/mini/guide-central-repository-upload.html

You need to generate a PGP key and update your maven configuration.

More insights: https://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by trajano** [comment]
I use this approach http://central.sonatype.org/pages/ossrh-guide.html for my own projects.  I also deploy the maven site to github pages using my wagon-git project.  http://site.trajano.net/trajano http://site.trajano.net/wagon-git

**Comment by trajano** [comment]
I'll take this over @otaviojava I'll set up the project for you on Maven.  The one I will release in my own groupId (net.trajano) once it is set up properly I will try to guide you to create your own GnuPG signing key so it would be under you signature rather than mine.

**Comment by otaviojava** [comment]
@trajano thank you.
