### ISSUE TITLE
Unable to update persisted Map<String,String>

### ISSUE THREAD

**Issue by siwatson** [otaviojava/Easy-Cassandra#39]
I have an entity with the following member:

@ElementCollection
@Column(name="fields")
private Map<String, String> fields;

I can persist the entity to Cassandra ok but, when I query it (using findOne) I can read the map keys/values but if I try adding another key-value, I see the following exception:

Exception in thread "main" java.lang.UnsupportedOperationException
    at java.util.Collections$UnmodifiableMap.put(Collections.java:1342)

It seems that EasyCassandra is giving me an immutable object back. Is this correct? 

What's the suggested approach for reading a record with a collection, updating the collection, and writing back to the DB?

**Comment by trajano** [comment]
try 
    new HashMap(existingMap);

**Comment by siwatson** [comment]
Thanks!
