### ISSUE TITLE
Support for multiple class mapping in one table via discriminator

### ISSUE THREAD

**Issue by ghost** [otaviojava/Easy-Cassandra#7]
Is there a support to allow multiple classes to be mapped to a single table via a discriminator column? 

For example:
@Entity
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "type", discriminatorType = DiscriminatorType.INTEGER)
public abstract Superclass

Then you can have multiple subclasses of one superclass mapped

@Entity
@DiscriminatorValue("3")
public Subclass1 extends SuperClass

@Entity
@DiscriminatorValue("2")
public Subclass2 extends SuperClass

**Comment by otaviojava** [comment]
Sorry by delay.
I believe not, it because Cassandra does on Family column structured, so there isn't relationship as SQL's data base. You must put this information on only one column family, so You should use the super mapped class instead see: http://goo.gl/y8dfeC
For more information, please, read the wiki: http://goo.gl/uMcOKA

Really thank you for your feedback, If have another thing, please let me know that.

**Comment by otaviojava** [comment]
Using your example: 

MappedSuperclass
public abstract Superclass

Super class has not a column family.

Bellow: Each class has own column family, defined with entity's annotation, both have super class attributes and its specific attributes.

@Entity
public Subclass1 extends SuperClass

@Entity
public Subclass2 extends SuperClass

**Comment by ghost** [comment]
Hi,

Thank you @otaviojava for your reply. Will the MappedSuperclass example you mentioned above allow me to have a single table that maps to 3 classes? I tried this initially and it failed. An example would be a table called animal with a column called type. If type is 1 then it gets mapped to Cat which is a subclass of the Animal abstract class, if type is 2 then it gets mapped to Dog which is another subclass of the Animal abstract class. Hector Object Mapper provides this type of inheritance but they are unfortunately not supporting CQL3 at the moment which is why I thought Easy Cassandra would be a better solution for us, if this type of inheritance could be supported. For more details of the Hector Object Mapper inheritance, please see http://hector-client.github.io/hector/build/html/content/HOM/hector-object-mapper.html#inheritance

Is there a way that Easy Cassandra could be extended to support this? Also, how does one contribute to this project? Thanks

**Comment by otaviojava** [comment]
Yes it's is possible to have something like that and you can participant how you want, maybe doing this features to the project.

**Comment by ghost** [comment]
What's the process for doing that? Do I just check out this project, add the features (and tests) then check in? What's the release schedule like and who does the QA?

Thanks again!

**Comment by otaviojava** [comment]
You do fork the project, do the improvement with test and request the pull request.

**Comment by ghost** [comment]
Hi @otaviojava,

I realized that my modeling was incorrect (based on what I'm after) so after I fixed it to satisfy my query needs, I was able to solve it using a combination of MappedSuperclass and EmbeddedId. However, I had to add the ability to query by primary key and index and also fixed a bug wherein the embedded id from the mapped superclass is not honored. 

These changes have been checked in to my forked branch and a pull request has been sent for it. The request has the summary of changes. Let me know. Thanks!

**Comment by otaviojava** [comment]
Wow! it is amazing, really thank you about this resource.
Do you have a blog? What do you think write about this resources?
When you have done, please, let me know to share to all in comunity.
